DROP DOMAIN PERMISSION_NN;
DROP TYPE PERMISSION;

DROP DOMAIN AUTHORITY_NN;
DROP TYPE AUTHORITY;

DROP DOMAIN UUID_NN;
DROP DOMAIN HSTORE_NN;
DROP DOMAIN TS_NN;
DROP DOMAIN INT_NN;
DROP DOMAIN TEXT_NN;
DROP DOMAIN TEXT_NZ;