version: '3'
services:
    postgres-server:
        container_name: postgres-server
        image: postgres
        expose:
            - "5432"
        volumes:
            - ../postgres/initdb.d:/docker-entrypoint-initdb.d
            - ../postgres/pgdata:/var/lib/postgresql/data
            - ../postgres/postgres.conf:/etc/postgresql/postgresql.conf
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
    pikit-graphql-server:
        container_name: pikit-graphql-server
        build: pikit-graphql-server
        expose:
            - "8000"
        volumes:
            - ../app/pikit-graphql-server:/app
        depends_on:
            - postgres-server
    pikit-restful-server:
        container_name: pikit-restful-server
        build: pikit-restful-server
        expose:
            - "8001"
        volumes:
            - ../app/pikit-restful-server:/app
        depends_on:
            - postgres-server
    pikit-web:
        container_name: pikit-web
        build: pikit-web
        ports:
            - "80:80"
        volumes:
            - ../app/pikit-web:/app
        depends_on: 
            - pikit-graphql-server
            - pikit-restful-server