version: '3'
services:
    postgres-server:
        container_name: postgres-server
        image: postgres
        expose:
            - "5432"
        volumes:
            - ../sql:/app
            - ../postgres/initdb.d:/docker-entrypoint-initdb.d
            - ../postgres/pgdata:/var/lib/postgresql/data
            - ../postgres/postgres.conf:/etc/postgresql/postgresql.conf
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
    pigskit-graphql-server:
        container_name: pigskit-graphql-server
        build: pigskit-graphql-server
        expose:
            - "8000"
        volumes:
            - ../app/pigskit-graphql-server:/app
        depends_on:
            - postgres-server
    pigskit-restful-server:
        container_name: pigskit-restful-server
        build: pigskit-restful-server
        expose:
            - "8001"
        volumes:
            - ../app/pigskit-restful-server:/app
        depends_on:
            - postgres-server
    pigskit-web:
        container_name: pigskit-web
        build: pigskit-web
        ports:
            - "80:80"
        volumes:
            - ../app/pigskit-web:/app
        depends_on: 
            - pigskit-graphql-server
            - pigskit-restful-server